name: Deploy to EC2 (build on server)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH → pull, build, restart
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |

                  set -euo pipefail

                  APP_ROOT=/var/www/Personal-Hub
                  FRONT_DIR=$APP_ROOT/client
                  BACK_DIR=$APP_ROOT/backend

                  # Ensure dirs & ownership
                  sudo mkdir -p "$APP_ROOT"
                  sudo chown -R "$USER":"$USER" "$APP_ROOT"

                  # --- pull latest code (use HTTPS to avoid needing a deploy key) ---
                  if [ -d "$APP_ROOT/.git" ]; then
                    cd "$APP_ROOT"
                    git remote set-url origin https://github.com/Jmjmorelli/Personal-Hub.git
                    git fetch --all --prune
                    git reset --hard origin/main
                  else
                    git clone https://github.com/Jmjmorelli/Personal-Hub.git "$APP_ROOT"
                    cd "$APP_ROOT"
                  fi

                  # --- frontend clean install & build ---
                  cd "$FRONT_DIR"
                  # nuke node_modules to avoid ENOTEMPTY
                  rm -rf node_modules
                  # optional: ensure cache is clean
                  npm ci --no-audit --no-fund
                  npm run build
                  
                  # --- backend clean install & restart ---
                  cd "$BACK_DIR"
                  rm -rf node_modules
                  npm ci --no-audit --no-fund
                  
                  # ensure pm2 exists (global install is fine)
                  if ! command -v pm2 >/dev/null 2>&1; then
                    sudo npm i -g pm2
                  fi

                  # Keep ports consistent with Nginx (proxy_pass -> 127.0.0.1:3001)
                  export NODE_ENV=production
                    export PORT=3001

                  pm2 describe personal-hub-backend >/dev/null 2>&1 \
                    && pm2 restart personal-hub-backend \
                      || pm2 start index.js --name personal-hub-backend --time

                  pm2 save || true
                    (pm2 startup systemd -u "$USER" --hp "$HOME" || true)

                  sudo nginx -t
                  sudo systemctl reload nginx